### ISSUE TITLE
can't fill primitives as blue

### ISSUE THREAD

**Issue by mreinstein** [mreinstein/cobalt#13]
doesn't seem to work, e.g., 

```javascript
pNode.filledBox([ 240, 170 ], 480, 340, [ 0.0, 0.0, 1.0, 1.0 ])
```

all the other colors work. why not blue??

**Comment by piellardj** [comment]
I don't reproduce on my machine, all I set all kinds of primitives blue and it works.

**Comment by mreinstein** [comment]
I'll see if I can reproduce this again on my side, it's been a while since I looked at it so the details are hazy. :)

**Comment by mreinstein** [comment]
I can't seem to repro this problem anymore.
